start
:obtener ROIS;

repeat
  :Obtener imagen;
  repeat :Para cada ROI xy;
  :Encontrar centros en ROIs __xy__;
  :Calcular desplazamientos **xy**;
  repeat while ()
  :Encontrar centro en ROIs __z__;
  :Calcular desplazamiento **z**;
  :generate diagrams;
   if (Algo mal) then (yes)
     :corregirlo;
  else (no)
     :cacarear;
   endif
   :caca;
backward:This is backward;
repeat while (more data?)

stop
@enduml
